version: '3.8'

services:
  tele-mcp:
    build: .
    ports:
      - "8090:8080"
    environment:
      - BOOT_COMMAND=uv tool install mcp-server-time
      - MCP_COMMAND=uvx mcp-server-time
      - DURABLE_MODE=true